# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjI5ZDQ4ZTgwZTM0NzYzNGMyODc4ZjljNTAyMTJkZTNmMzM2YmM2ZDQzZjRlODU5ZGU1OWE4MTQ4NzU4MWQ0ODE5MzViYWM1ZDUxNTZhOTA5MDY4MDM3MjU5MjM2NjU4NzZmMWM5NGY1YmM4Y2EzOWQwMmUwOTQwZGY2NmY5MTI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
